apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
  labels:
    app: backend-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
      - image: dotrunghieu96/udagram-api-feed
        name: backend-feed 
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: URL
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: URL 
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: POSTGRES_DB
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: POSTGRES_HOST
        - name: POSTGRESS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: POSTGRESS_PASSWORD
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: JWT_SECRET
        - name: POSTGRESS_USERNAME
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: POSTGRESS_USERNAME
      restartPolicy: Always
      volumes:
      - name: aws-secret
        secret:
          secretName: aws-secret